### ISSUE TITLE
Заменить использование float в уроке "Магические числа"

### ISSUE THREAD

**Issue by dzencot** [hexlet-basics/exercises-cpp#108]
https://code-basics.com/ru/languages/cpp/lessons/magic-numbers#editor - в уроке используется тип float, про который еще не говорилось в курсе. Нужно заменить на что-то другое. Так же в задании тоже заменить.

**Comment by usernaimandrey** [comment]
https://github.com/hexlet-basics/exercises-cpp/commit/9b7d326df3c39ad6a1fd9a0fe806471caf1a56cd
