### ISSUE TITLE
Ошибка в примере!

### ISSUE THREAD

**Issue by SmorThy** [hexlet-basics/exercises-cpp#109]
В уроке C++: Целочисленные типы в примере вывода(в задании) написано:   87000 seconds = 1 days - что не является верным, так-как в одном дне 86400 секунд, из-за этого пользователи будут ломать себе голову в решении данного задания!
![Screenshot 2023-08-09 140027](https://github.com/hexlet-basics/exercises-cpp/assets/113018282/301fbc62-ca4f-42cf-87f9-10ee515f3f5d)

**Comment by usernaimandrey** [comment]
https://github.com/hexlet-basics/exercises-cpp/commit/022e5f58cfa996bdb6a5ab2a26a85c36cf35ffd7
