### ISSUE TITLE
Проверить Вывод результата на экран

### ISSUE THREAD

**Issue by fey** [hexlet-basics/exercises-cpp#49]
Студенты прислали фидбек, что на экран (там где вывод тестов например) не выводится результат печати на экран (stdout).
Нужно проверить, так ли это.
Логика должна быть по аналогии с другими стеками. Когда сперва выводится то, что на stdout попадает, потом вывод тестов.

**Comment by usernaimandrey** [comment]
https://github.com/hexlet-basics/exercises-cpp/pull/50

**Comment by usernaimandrey** [comment]
Да выводилось только если тест падал
