### ISSUE TITLE
Перенести сюда курс по си с Хекслета

### ISSUE THREAD

**Issue by mokevnin** [hexlet-basics/exercises-cpp#5]
https://ru.hexlet.io/courses/introduction_to_c

**Comment by zhabinka** [comment]
@mokevnin курс по Си перенесли вот сюда – https://github.com/hexlet-basics/exercises-clang/issues
Здесь что-то нужно делать?

**Comment by zhabinka** [comment]
@mokevnin предлагаешь его на плюсы переделать?

**Comment by mokevnin** [comment]
cpp это плюсы

**Comment by zhabinka** [comment]
Ага. На Хекслете есть видео-курс по C. Мы его уже перенесли на CB. А что здесь нужно сделать?

**Comment by fey** [comment]
Делается в рамках репо https://github.com/hexlet-basics/exercises-clang
