### ISSUE TITLE
Неверная ссылка в 'About'

### ISSUE THREAD

**Issue by AlexanderAverin** [hexlet-basics/exercises-cpp#51]
В поле 'About' указана ссылка на курс по Clang. Нужно заменить эту ссылку на вот эту https://code-basics.com/ru/languages/cpp

**Comment by 21aLeX** [comment]
Я беру!

**Comment by fey** [comment]
@21aLeX скорее всего вы не сможете это пофиксить, тк это в описании репозитория. На него нужны права.
@amshkv Андрей, поправь, пожалуйста в описании репо ссылку на КБ
![image](https://github.com/hexlet-basics/exercises-cpp/assets/697178/e45d5d80-3c1a-42be-a952-5043fe267ee2)
