### ISSUE TITLE
Неверное отображение - глава char

### ISSUE THREAD

**Issue by BungaaFACE** [hexlet-basics/exercises-cpp#56]
Проходил главу про char. Если брать решение от учителя, то выводится ответ явно не нормальной кирилицей.
Test Passed!!!
Ð­
А если попробовать тот же код выполнить в VS Code(g++), то выводится пустая строка.

#include <iostream>

int main() {
  // BEGIN
  setlocale(LC_ALL, "ru_RU");
  wchar_t symbol = L'Э';
  std::wcout << symbol << std::endl;
  return 0;
  // END
}

офтопик, но личное негодование: в задании требуется использовать префикс L'*', про которые еще не объясняли.

**Comment by usernaimandrey** [comment]
Привет!
> А если попробовать тот же код выполнить в VS Code(g++), то выводится пустая строка

Можете показать как вы компилируете свой код и какая операционка у вас

**Comment by BungaaFACE** [comment]
cStandart c17
cppStandart c++17
"compilerPath": "C:\\mingw64\\bin\\g++.exe"
Windows 10

tasks:
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: g++.exe build active file",
            "command": "C:\\mingw64\\bin\\g++.exe",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": "build",
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"

Компилирую в VS Code 1.76.2  с компилятором minGW64.

C:\mingw64\bin>g++ --version
g++ (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders) 12.2.0

**Comment by ssssank** [comment]
@usernaimandrey тыц

**Comment by usernaimandrey** [comment]
@ssssank https://github.com/hexlet-basics/exercises-cpp/commit/e7d21e42097b5409670878781a34c0e72ad91fe2 поменял условие и код
