### ISSUE TITLE
Ошибка в задаче exercises-cpp/modules/40-data-types/40-floating-type

### ISSUE THREAD

**Issue by Livsnekad42** [hexlet-basics/exercises-cpp#60]
Решение некорректно, либо ошибка в условии. Ожидается ответ 48.8, и объём бака почему-то умножается на 10. Хотя по условиям объём 43 и расход 8.8л/км.

**Comment by sgmdlt** [comment]
@usernaimandrey Посмотри, может там опечатка?

**Comment by ssssank** [comment]
Кажется, ошибки здесь нет. Ответ правильный. Умножить на 10 можно как сразу объём бака, так и результат деления

**Comment by usernaimandrey** [comment]
Условие было не неверным, поправил
